### ISSUE TITLE
Having an error and no messeges recieved

### ISSUE THREAD

**Issue by l3op** [fraineralex/chatify#11]
Hello there,

I tried to run the project on my localhost and i had some issue. For the client side working just fine. i set Auth0 environment variables and i'm able to login and register. Chat are not received or sent . Like it's pending.

![image](https://github.com/user-attachments/assets/db965516-0c60-4bca-860f-912d575d3584)

Server side i noticed some error saying:

 ```
[1] [nodemon] starting `node dist/index.js dist/index.js`
[1] Server is running in port 3000
[1] GET /api/users/metadata 304 1850.953 ms - -
[1] JsonWebTokenError: secret or public key must be provided
[1]     at C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:113:19
[1]     at getSecret (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:97:14)
[1]     at module.exports [as verify] (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:101:10)
[1]     at authSocketMiddleware (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/middlewares/auth.js:17:29)
[1]     at Array.<anonymous> (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/router/socket.js:10:39)
[1]     at run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:124:19)
[1]     at Namespace.run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:135:9)
[1]     at Namespace._add (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:211:14)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] GET /api/users/metadata 304 1026.164 ms - -
[1] JsonWebTokenError: secret or public key must be provided
[1]     at C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:113:19
[1]     at getSecret (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:97:14)
[1]     at module.exports [as verify] (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:101:10)
[1]     at authSocketMiddleware (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/middlewares/auth.js:17:29)
[1]     at Array.<anonymous> (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/router/socket.js:10:39)
[1]     at run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:124:19)
[1]     at Namespace.run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:135:9)
[1]     at Namespace._add (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:211:14)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] GET /api/chats 304
```

I wonder if this issue related to Socket or i missed configuring Auth0 Management API.

Could you please guide me how to fix this issue.

Best regards.

**Comment by fraineralex** [comment]
> Hello there,
> 
> I tried to run the project on my localhost and i had some issue. For the client side working just fine. i set Auth0 environment variables and i'm able to login and register. Chat are not received or sent . Like it's pending.
> 
> ![image](https://private-user-images.githubusercontent.com/12974004/397193223-db965516-0c60-4bca-860f-912d575d3584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4OTg4OTMsIm5iZiI6MTczNDg5ODU5MywicGF0aCI6Ii8xMjk3NDAwNC8zOTcxOTMyMjMtZGI5NjU1MTYtMGM2MC00YmNhLTg2MGYtOTEyZDU3NWQzNTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDIwMTYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YTU0MTdiZDE4ODM1NWIwZTI5N2I5YjY0ODhkYmFlZjY5ZTA3NGVlNTAzY2I0MGVhNGFmNmZhZDA3ZTEzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mYQHCtdLYEb3XWOt5eTjqibvW4565tptNwQ3HNmMp20)
> 
> Server side i noticed some error saying:
> 
> ```
> [1] [nodemon] starting `node dist/index.js dist/index.js`
> [1] Server is running in port 3000
> [1] GET /api/users/metadata 304 1850.953 ms - -
> [1] JsonWebTokenError: secret or public key must be provided
> [1]     at C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:113:19
> [1]     at getSecret (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:97:14)
> [1]     at module.exports [as verify] (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:101:10)
> [1]     at authSocketMiddleware (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/middlewares/auth.js:17:29)
> [1]     at Array.<anonymous> (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/router/socket.js:10:39)
> [1]     at run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:124:19)
> [1]     at Namespace.run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:135:9)
> [1]     at Namespace._add (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:211:14)
> [1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [1] GET /api/users/metadata 304 1026.164 ms - -
> [1] JsonWebTokenError: secret or public key must be provided
> [1]     at C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:113:19
> [1]     at getSecret (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:97:14)
> [1]     at module.exports [as verify] (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\jsonwebtoken\verify.js:101:10)
> [1]     at authSocketMiddleware (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/middlewares/auth.js:17:29)
> [1]     at Array.<anonymous> (file:///C:/Users/MSI/Desktop/l3op/chatify/server/dist/src/router/socket.js:10:39)
> [1]     at run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:124:19)
> [1]     at Namespace.run (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:135:9)
> [1]     at Namespace._add (C:\Users\MSI\Desktop\l3op\chatify\server\node_modules\socket.io\dist\namespace.js:211:14)
> [1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [1] GET /api/chats 304
> ```
> 
> I wonder if this issue related to Socket or i missed configuring Auth0 Management API.
> 
> Could you please guide me how to fix this issue.
> 
> Best regards.

Hi there,

Thanks for the detailed description of the issue. From the error message, it looks like the problem might be related to a missing environment variable for the Auth0 Management API token.

I realized I forgot to include the `AUTH0_MGMT_API_TOKEN` variable in the `.env.example` file. I've now updated the file and pushed the changes to the repository. Please pull the latest changes, add your Auth0 Management API token to the `.env` file, and try running the project again locally.

Let me know if this resolves the issue or if you're still facing any problems!

Best regards,  
Frainer

**Comment by l3op** [comment]
Hello there, I really appreciate your response. 


I guess **AUTH0_MGMT_API_TOKEN** isn't related to the the issue at all.

I was debugging the code and i noticed that the problem is might related to this couple line code.
https://github.com/fraineralex/chatify/blob/55ac273143286e49ff3a0e8a7a8eaa38acfe85d8/server/src/middlewares/auth.ts#L6
https://github.com/fraineralex/chatify/blob/55ac273143286e49ff3a0e8a7a8eaa38acfe85d8/server/src/middlewares/auth.ts#L22

I'm just wondering, What's the **AUTH0_PUBLIC_SIGNING_KEY** should be?

Regards

**Comment by fraineralex** [comment]
> Hello there, I really appreciate your response.
> 
> I guess **AUTH0_MGMT_API_TOKEN** isn't related to the the issue at all.
> 
> I was debugging the code and i noticed that the problem is might related to this couple line code.
> 
> https://github.com/fraineralex/chatify/blob/55ac273143286e49ff3a0e8a7a8eaa38acfe85d8/server/src/middlewares/auth.ts#L6
> 
> 
> https://github.com/fraineralex/chatify/blob/55ac273143286e49ff3a0e8a7a8eaa38acfe85d8/server/src/middlewares/auth.ts#L22
> 
> I'm just wondering, What's the **AUTH0_PUBLIC_SIGNING_KEY** should be?
> 
> Regards

Here's a response you can post to clarify the issue and guide them:

---



> Hello there, I really appreciate your response.
> 
> I guess **AUTH0_MGMT_API_TOKEN** isn't related to the the issue at all.
> 
> I was debugging the code and i noticed that the problem is might related to this couple line code.
> 
> https://github.com/fraineralex/chatify/blob/55ac273143286e49ff3a0e8a7a8eaa38acfe85d8/server/src/middlewares/auth.ts#L6
> 
> 
> https://github.com/fraineralex/chatify/blob/55ac273143286e49ff3a0e8a7a8eaa38acfe85d8/server/src/middlewares/auth.ts#L22
> 
> I'm just wondering, What's the **AUTH0_PUBLIC_SIGNING_KEY** should be?
> 
> Regards

Hi there,

The `AUTH0_PUBLIC_SIGNING_KEY` is a public key used to verify the JWT signature. You can find it in the Auth0 dashboard by navigating to **Applications** -> **Your application** -> **Settings** -> **Advanced Settings** (at the bottom) -> **Certificates** -> **Signing Certificate**.

Once you have the key, set it in your `.env` file as `AUTH0_PUBLIC_SIGNING_KEY`. Be sure to include the full certificate, which should have `-----BEGIN CERTIFICATE-----` at the beginning and `-----END CERTIFICATE-----` at the end of the key.

Let me know if this resolves your issue!

Regards
